Importing open ai gym and the package

In [1]:
import gym
import numpy as np
import airline

Define the function for evaluating the model on a given environment for a specified number of episodes. 

In [2]:
def evaluate(model, env, numiters):
    rewards = []
    for j in range(numiters):
        env.reset()
        tot_reward = 0
        for i in range(env.tau):
            _, reward, _, _ = env.step(model(env), i)
            tot_reward += reward
        rewards.append(tot_reward)
    return np.mean(rewards), np.std(rewards)

# Model is the random policy
def policy(env):
    return env.action_space.sample()
    

Setting up the configuration for the environment

In [3]:
A = np.asarray([[1, 1, 0,0,0,0], [ 0,0, 1, 1, 1, 1], [ 0,0, 0,0, 1, 1] ])
tau = 23
P = np.ones((tau, A.shape[1]))/3
c = [5, 5, 5]
f = range(10, 16)
CONFIG = {'A': A, 'f': f, 'P': P, 'starting_state': c , 'tau': tau}

Making an instance of the environment

In [4]:
env = gym.make('Airline-v0', config=CONFIG)

Testing the variables

In [5]:
print(env.state)
print(env.action_space)
print(env.observation_space) # openAI calles states observations :/

[6 6 6]
MultiDiscrete([2 2 2 2 2 2])
MultiDiscrete([6 6 6])


Testing the step function

In [6]:
env.state = [1,0, 0]
print(env.step(np.asarray([1,1, 1, 1, 1, 1]), 5))
print('***')
env.state = [3, 3, 3]
print(env.step([1,1, 1, 1, 1, 1], 5))

(array([1, 0, 0]), 0, False, {})
***
(array([3, 2, 3]), 11, False, {})


test sample uniformly from action space at random

In [7]:
env.action_space.sample()

array([0, 0, 1, 1, 1, 1])

Simulating randomized policy

In [8]:
N = 50
e = 23
rewards = []
for j in range(e):
    env.reset()
    tot_reward = 0
    for i in range(tau):
        _, reward, _, _ = env.step(env.action_space.sample(), i)
        tot_reward += reward
    rewards.append(tot_reward)

Test Evaluate Function

In [9]:
print('Here is the mean and standard deviation of the estimate ' + str(evaluate(policy, env, 50)))

Here is the mean and standard deviation of the estimate (105.38, 8.546086823804215)
